name: LengLeng
options:
  bundleIdPrefix: com.lengleng
  deploymentTarget:
    iOS: 15.0
targets:
  LengLeng:
    type: application
    platform: iOS
    sources:
      - path: LengLeng
        excludes:
          - "Sources/**"
    resources:
      - path: LengLeng/GoogleService-Info.plist
    settings:
      base:
        INFOPLIST_FILE: LengLeng/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lengleng.app
        TARGETED_DEVICE_FAMILY: 1,2
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - framework: SwiftUI.framework
      - framework: UIKit.framework
    packages:
      - url: https://github.com/firebase/firebase-ios-sdk
        version: 11.11.0
        products:
          - FirebaseCore
          - FirebaseAuth
          - FirebaseFirestore
          - FirebaseFirestoreSwift
          - FirebaseStorage
      - url: https://github.com/onevcat/Kingfisher
        version: 7.0.0
        products:
          - Kingfisher
      - url: https://github.com/SDWebImage/SDWebImageSwiftUI
        version: 2.0.0
        products:
          - SDWebImageSwiftUI
 