name: LengLeng
options:
  bundleIdPrefix: com.lengleng
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"
targets:
  LengLeng:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources/LengLeng/LengLengMainApp.swift
      - path: Sources/LengLeng/Views/MainContentView.swift
      - path: Sources/LengLeng/Views/QuestionView.swift
      - path: Sources/LengLeng/Models
      - path: Sources/LengLeng/Services
      - path: Sources/LengLeng/Features
      - path: Sources/LengLeng/Utils
    settings:
      base:
        INFOPLIST_FILE: Sources/LengLeng/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lengleng.app
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Sources/LengLeng/Info.plist
      properties:
        UILaunchStoryboardName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    resources:
      - path: Sources/LengLeng/Config/GoogleService-Info.plist
        type: file
    dependencies:
      - package: firebase-ios-sdk
      - package: Kingfisher
      - package: SDWebImageSwiftUI
packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
    products:
      - FirebaseAuth
      - FirebaseFirestore
      - FirebaseStorage
      - FirebaseAnalytics
      - FirebaseMessaging
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.0.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI.git
    from: 3.0.0 